FROM node:latest AS build
# Create a Virtual directory inside the docker image
WORKDIR /dist/src/app
# Copy files to virtual directory
# COPY package.json package-lock.json ./
# Run command in Virtual directory
RUN npm cache clean --force
# Copy files from local machine to virtual directory in docker image
COPY ./ .
RUN npm install
RUN npm run build 

FROM nginx:latest AS ngi
COPY --from=build /dist/src/app/dist/audio-transcriber /usr/share/nginx/html
#COPY /nginx.conf  /etc/nginx/conf.d/default.conf
#COPY ./index.html /usr/share/nginx/html/index.html
#WORKDIR /usr/share/nginx/html
EXPOSE 80
#ARG REGION
#ENV REGION=${REGION}
#RUN echo "Deployed on Region : ${REGION}" >> /usr/share/nginx/html/index.html
#RUN echo "<br>" >> /usr/share/nginx/html/index.html
#RUN date +"%A, %b %d, %Y %H:%M:%S" >> /usr/share/nginx/html/index.html
